### ISSUE TITLE
Resolve topicref URI is not working when @chunk=''to-content" is specified

### ISSUE THREAD

**Issue by naguila** [dita-community/org.dita-community.common.xslt#12] opened 2015-07-10 22:34 UTC
When topics are being reused several times in a given book and chunk is specified as "to-content", the transformation fails to resolve the correct topic URI using the function df:resolveTopicRef(). If the chunk attribute is specified as "to-content select-branch", the transformation finish correctly.

This scenario is present when using dc-preprocess and adjust-copy is enabled to automatically generate @copy-to for reused topics. The resolved URI points to the @copy-to  when should be to the ancestor with @chunk.

Support for "to-content" is needed.

bookmap example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookmap PUBLIC "-//OASIS//DTD DITA BookMap//EN" "bookmap.dtd">
<bookmap>
    <booktitle>
        <mainbooktitle></mainbooktitle>
    </booktitle>
    <chapter chunk="to-content" href="topics/topic1.dita">
        <topicref href="topics/topic3.dita"/>
    </chapter>
    <chapter chunk="to-content" href="topics/topic2.dita">
        <topicref href="topics/topic3.dita"/>
    </chapter>
</bookmap>
```

**Comment by drmacro** [comment] 2015-07-11 16:10
Good catch. I'll get this fixed as soon as I can.

**Comment by drmacro** [comment] 2015-07-14 16:46
Either I don't understand the failure or I can't reproduce it.

What is the actual failure symptom that you're seeing?

I created a test case that I think replicates your sample bookmap and I get the correct generated copy-to values on the topicrefs that specify @chunk="to-content" and the resulting HTML output is correct as far as I can see.

**Comment by drmacro** [comment] 2015-07-14 16:50
I have found the relevant code in df:inChunk():

````
    <xsl:variable name="result" as="xs:boolean"
      select="contains($chunkSpec, 'to-content') and
              (contains($chunkSpec, 'select-branch') or
               contains($chunkSpec, 'select-document'))"
    />
````

This code would behave as you report.

**Comment by naguila** [comment] 2015-07-14 17:04
Calling df:resolveTopicRef() function in custom templates raise the error. I could trace it to the df:inChunk() function as you mention.

**Comment by drmacro** [comment] 2015-07-14 17:11
I've pushed a fix to the develop branch. Can you get this and test in your environment?

**Comment by drmacro** [comment] 2015-07-14 17:29
I created a little test and based on that I believe the behavior is now correct.

**Comment by naguila** [comment] 2015-07-14 17:49
Now it works as expected. Thank you.

**Comment by drmacro** [comment] 2015-07-14 17:50
Cool. I'm preparing a release package but I have a couple of other high-priority bugs I want to put in it. Can you get by with the development version of the plugin for now?

**Comment by naguila** [comment] 2015-07-14 17:53
Sure, that will work in the meantime. Thanks.

**Comment by drmacro** [comment] 2015-09-12 16:53
Fix delivered in D4P RC14 or 15.

**Closed** 2015-09-12 16:53 UTC
Labels: bug
